python update_edifact_dicts.py EDIFACT_D00A
python update_edifact_dicts.py EDIFACT_D00B
python update_edifact_dicts.py EDIFACT_D01A
python update_edifact_dicts.py EDIFACT_D01B
python update_edifact_dicts.py EDIFACT_D01C
python update_edifact_dicts.py EDIFACT_D02A
python update_edifact_dicts.py EDIFACT_D02B
python update_edifact_dicts.py EDIFACT_D03A
python update_edifact_dicts.py EDIFACT_D03B
python update_edifact_dicts.py EDIFACT_D04A
python update_edifact_dicts.py EDIFACT_D04B
python update_edifact_dicts.py EDIFACT_D05A
python update_edifact_dicts.py EDIFACT_D05B
python update_edifact_dicts.py EDIFACT_D06A
python update_edifact_dicts.py EDIFACT_D06B
python update_edifact_dicts.py EDIFACT_D07A
python update_edifact_dicts.py EDIFACT_D07B
python update_edifact_dicts.py EDIFACT_D08A
python update_edifact_dicts.py EDIFACT_D08B
python update_edifact_dicts.py EDIFACT_D09A
python update_edifact_dicts.py EDIFACT_D09B
python update_edifact_dicts.py EDIFACT_D10A
python update_edifact_dicts.py EDIFACT_D10B
python update_edifact_dicts.py EDIFACT_D11A
python update_edifact_dicts.py EDIFACT_D11B
python update_edifact_dicts.py EDIFACT_D12A
python update_edifact_dicts.py EDIFACT_D12B
python update_edifact_dicts.py EDIFACT_D13A
python update_edifact_dicts.py EDIFACT_D13AV4
python update_edifact_dicts.py EDIFACT_D13B
python update_edifact_dicts.py EDIFACT_D13BV4
python update_edifact_dicts.py EDIFACT_D14A
python update_edifact_dicts.py EDIFACT_D14AV4
python update_edifact_dicts.py EDIFACT_D14B
python update_edifact_dicts.py EDIFACT_D14BV4
python update_edifact_dicts.py EDIFACT_D15A
python update_edifact_dicts.py EDIFACT_D15AV4
python update_edifact_dicts.py EDIFACT_D15B
python update_edifact_dicts.py EDIFACT_D15BV4
python update_edifact_dicts.py EDIFACT_D16A
python update_edifact_dicts.py EDIFACT_D16AV4
python update_edifact_dicts.py EDIFACT_D93A
python update_edifact_dicts.py EDIFACT_D94A
python update_edifact_dicts.py EDIFACT_D94B
python update_edifact_dicts.py EDIFACT_D95A
python update_edifact_dicts.py EDIFACT_D95B
python update_edifact_dicts.py EDIFACT_D96A
python update_edifact_dicts.py EDIFACT_D96B
python update_edifact_dicts.py EDIFACT_D97A
python update_edifact_dicts.py EDIFACT_D97B
python update_edifact_dicts.py EDIFACT_D98A
python update_edifact_dicts.py EDIFACT_D98B
python update_edifact_dicts.py EDIFACT_D99A
python update_edifact_dicts.py EDIFACT_D99B
